# These are supported funding model platforms

custom: ['https://cryinkfly.com/sponsoring/', 'https://www.paypal.com/donate/?hosted_button_id=TBVAGT45LMR6W', 'https://www.amazon.de/hz/wishlist/ls/MOK18Y12W61L#']
